### ISSUE TITLE
Storm naming

### ISSUE THREAD

**Issue by joewalderman** [BrennieDev/issues-lab#2]
https://github.com/BrennieDev/issues-lab/blob/2eaee5505c578362af8df24b5b3d0bb1535b4fa3/got_issues.Rmd#L23

Storms should be changed to "storm" in this line

**Comment by ianbrunjes** [comment]
Looks like 'storms' is the correct naming, but actually raises an issue on line 18
https://github.com/BrennieDev/issues-lab/blob/2eaee5505c578362af8df24b5b3d0bb1535b4fa3/got_issues.Rmd#L18
